@echo off
setlocal
rem Generated by Makefile from scripts/run-playtest-launcher.bat.in — do not edit by hand.
"%~dp0playtest-launcher-a0.0.7+6-windows-amd64.exe" %*
set ERR=%ERRORLEVEL%
echo.
if %ERR% neq 0 (
  echo Exit code %ERR% ^(launcher or game^).
  pause
)
exit /b %ERR%
